#!/bin/bash
# 2. Write a script which delete an ACTIVE user on the VM.


read -p 'Choose a logged user to delete.. ' usertodel

echo "\nIs the user: $usertodel logged ??" 
echo ...
echo ......
echo .........
if $(ps aux | cut -d ' ' -f1 | grep -q $usertodel);
        then
        echo yes
        read -p "Do you confirm you want to delete the user : $usertodel (y/n) ? " answer
        if [ $answer = "y" ]
                then
                kilall -u $usetodel
                userdel -rf $usertodel > /dev/null 2>&1
                echo "OK delete complete.."
        else
                echo "Delete Canceled.."
        fi
else
        echo no
fi