#!/bin/bash
# 2. Write a script which delete an ACTIVE user on the VM.

ynloop=true;
read -p 'Choose a logged user to delete.. ' usertodel

echo "\nIs the user: $usertodel logged ??" 
echo ...
sleep 0.5s
echo ......
sleep 0.5s
echo .........
if $(ps aux | cut -d ' ' -f1 | grep -q $usertodel);
        then
        echo yes
	while $ynloop; do
	ynloop=false;
        read -p "Do you confirm you want to delete the user : $usertodel (y/n) ? " answer
        if [ $answer = "y" ]
                then
                kilall -u $usetodel > /dev/null 2>&1
                userdel -rf $usertodel > /dev/null 2>&1
		echo ...
		sleep 1s
                echo "OK delete complete.."
        elif [ $answer = "n" ]
		then
                echo "Delete Canceled.."
	else
		echo "Invalid input.."
		ynloop=true;
	
        fi
	done
else
	echo no
fi
