#!/bin/bash

helptext()
{
	clear
	echo Welcome to 03 script of Nsalle\'s Init project
	echo This script is composed of several mini utility scripts, and is supposed to be growing with time
	echo At the moment what you can do is:
	echo 
	echo -------- 1. Cache
	echo 
	echo It is used to clear the cache of your MAC session at a 42 school.
	echo Sometimes you won\'t be able to do anything on your session because it is full,
	echo when it happens you can only clear your own files, or clear the useless part of the cache manually.
	echo This script will just do it quicker for you.
	echo Of course it doesn\'t work on a debian system, so it will check if you are on a VM or on your MAC session.
	echo
	echo -------- 2. Bot
	echo
	echo If you feel alone, you can try to have a conversation with this stupid bot.
	echo It\'t only purpose for me was to practice Bash, and fill the menu a little bit.
	echo
	echo TO BE CONTINUED...
}

wtf()
{
	if [ $1 = '1' ]
	then
		echo "I don\'t understand what you say, can you talk a bit clearer please ??"
		return '2'
	else
		echo "Well I see you don't want to be serious, go back yo your terminal then !"
		exit
	fi
}

bot()
{
	echo
	echo
	echo Hello human
	sleep 1s
	echo "So, are you feeling alone enough to talk to a robot ? (y/n)"
	read answer
	if [ $answer = 'y' ]
	then
		echo
	elif [ $answer = 'n' ]
	then
		echo Aaahh happy for you, i let you go back to your work then !
		exit
	else
		wtf 1
		echo I will take it as a Yes..
	fi
	sleep 1s
	echo HAHA
	sleep 0.5s 
	echo I won\'t be a great help mate, i don\'t have so many lines, my creator had to finish his project ASAP

}

usage()
{
	echo "./03 [ -c -b ]"
	echo "./03 without options to open a menu"
	echo " Don't use more than one option"
}

cache()
{
	if $(ls /etc | grep -q debian_version);
	then
		echo This command will not work on a debian system, it is supposed to clean you session on a MAC at school
	else
		# Integrer ici le script de nettoyage de session
		echo Cache is cleared
	fi
}

menu()
{
	while [ 1 ]; do
	clear
	echo ''
	echo "                          ----MENU----                            "
	echo ''
	echo 'Type the number, or the name of the script you want to execute..'
	echo ''
	echo "1. Clear (cache)          2. Bot (If you feel alone..)"
	echo "3. Help			4. TBD"
	echo "0. Exit"
	echo ''
	read choice

	if [[ $choice = "1" ]] || [[ $choice = "Clear" ]];
	then
		cache
	elif [[ $choice = "0" ]];
	then
		exit
	elif [[ $choice = "2" ]] || [[ $choice = "Bot" ]];
	then
		bot
	elif [[ $choice = "3" ]] || [[ $choice = "Help" ]];
	then
		helptext
	fi
	read -p 'Press ENTER to continue..' reset
	done
}

if [ $# = 1 ];
then
	if [ $1 = "-c" ]
	then
		cache
	elif [ $1 = "-b" ]
	then
		bot
	else
		usage
	fi
elif [ $# = 0 ];
then
	menu
else
	usage
fi
